services:
  - type: web
    name: rollout-webhooks-demo
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ROLLOUT_CLIENT_ID
        sync: false
      - key: ROLLOUT_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
